### ISSUE TITLE
Does Ydbf plan to support foxbase dbf format?

### ISSUE THREAD

**Issue by rocketmangw** [y10h/ydbf#4]
There is no solution on pypi which can open and read foxbase dbf file.

Does Ydbf have plan to support this dbf format?

**Comment by y10h** [comment]
Hi

I appreciate your patience with me not following github notifications for a few years :) 

I don't work with dbf files at my dayjob anymore, and thus I don't have active plans for the development. http://www.independent-software.com/dbase-dbf-dbt-file-format.html suggests that there might be incremental changes from dbase 3 to foxpro to support forxpro, but I don't have sample files for foxpro to verify implementation.

If you're still interested in the feature and have a few samples of the files (preferably the ones that I can use as a test data and which don't include proprietary data), please let me know.

**Comment by y10h** [comment]
I'm closing it as expired.
